### ISSUE TITLE
Connecting to mongodb instance via "mongodb+srv://" causes error

### ISSUE THREAD

**Issue by jammm** [edemaine/coauthor#472]
Hello!

Thank you very much for this amazing project.

I'm trying to deploy this on heroku, and I believe I have set everything okay, but I get the following error on deployment:

`2020-06-17T12:16:13.167459+00:00 app[web.1]: Error: invalid schema, expected mongodb
2020-06-17T12:16:13.167460+00:00 app[web.1]: at module.exports (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/edemaine_file-collection/node_modules/mongodb/lib/url_parser.js:20:11)
2020-06-17T12:16:13.167461+00:00 app[web.1]: at connect (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/edemaine_file-collection/node_modules/mongodb/lib/mongo_client.js:159:16)
2020-06-17T12:16:13.167462+00:00 app[web.1]: at MongoClient.connect (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/edemaine_file-collection/node_modules/mongodb/lib/mongo_client.js:110:3)
2020-06-17T12:16:13.167462+00:00 app[web.1]: at packages/meteor.js:306:21
2020-06-17T12:16:13.167463+00:00 app[web.1]: at new FileCollection (packages/edemaine:file-collection/src/gridFS_server.js:45:15)
2020-06-17T12:16:13.167463+00:00 app[web.1]: at module (lib/files.coffee:7:10)
2020-06-17T12:16:13.167464+00:00 app[web.1]: at fileEvaluate (packages/modules-runtime.js:336:7)
2020-06-17T12:16:13.167464+00:00 app[web.1]: at Module.require (packages/modules-runtime.js:238:14)
2020-06-17T12:16:13.167464+00:00 app[web.1]: at require (packages/modules-runtime.js:258:21)
2020-06-17T12:16:13.167465+00:00 app[web.1]: at /app/.meteor/heroku_build/app/programs/server/app/app.js:8598:1
2020-06-17T12:16:13.167465+00:00 app[web.1]: at /app/.meteor/heroku_build/app/programs/server/boot.js:401:38
2020-06-17T12:16:13.167465+00:00 app[web.1]: at Array.forEach (<anonymous>)
2020-06-17T12:16:13.167465+00:00 app[web.1]: at /app/.meteor/heroku_build/app/programs/server/boot.js:226:21
2020-06-17T12:16:13.167466+00:00 app[web.1]: at /app/.meteor/heroku_build/app/programs/server/boot.js:464:7
2020-06-17T12:16:13.167466+00:00 app[web.1]: at Function.run (/app/.meteor/heroku_build/app/programs/server/profile.js:280:14)
2020-06-17T12:16:13.167466+00:00 app[web.1]: at /app/.meteor/heroku_build/app/programs/server/boot.js:463:13`

The issue arises from the driver version not supporting "mongodb+srv" in the mongodb uri string. It seems to have been implemented in npm-nodejs 3.x, which is included in the 1.9.2 version of meteor, but as you can see from the backtrace, the error comes from an older, 2.x version of mongodb driver used in "edemaine:file-collection".

Is it possible to update the driver version in that package? It seems like a private package, so I can't access it. I could be wrong though.

**Comment by edemaine** [comment]
Hmm, this is new; other people have recently deployed Coauthor without issue.  Could you clarify what you think is the trouble here, for example, a new version of MongoDB that doesn't support the `mongodb+srv` protocol? [This documentation](https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format) suggests it's still a valid thing. Perhaps there is something about Heroku that means `+srv` should be omitted?

I can certainly try updating the dependencies in [`edemaine:file-collection`](https://github.com/edemaine/meteor-file-collection) but it'd be nice to know that this will actually fix the problem (and not e.g. introduce new bugs)...

Can you specify which version of MongoDB you're using, and which version of Meteor if you've changed from what's in this repo?

**Comment by jammm** [comment]
Thanks a lot for your quick reply !

Sorry, I should have specified the MongoDB versions earlier. I'm currently using MongoDB atlas, which is a DBaaS provided by MongoDB. The version of MongoDB it uses is 4.2.6 it seems.

The issue is that the driver version that supports `+srv` is 3.0 or later, which means that https://github.com/edemaine/meteor-file-collection doesn't support it, as it uses driver version 2.1.21 - https://github.com/edemaine/meteor-file-collection/blob/master/package.js#L18

A potential fix could be to update the driver version of the meteor file collection. I could try updating it for my own situation and make it work like that perhaps, in order to avoid potentially breaking anything for other users.

Cheers!

**Comment by jammm** [comment]
Thanks a lot for your quick reply !

Sorry, I should have specified the MongoDB versions earlier. I'm currently using MongoDB atlas, which is a DBaaS provided by MongoDB. The version of MongoDB it uses is 4.2.6 it seems. I'm using Meteor `1.9.2` which is the same one this repo came with. I did try updating Meteor to `1.10.2` but I get the same issue.

The issue is that the driver version that supports `+srv` is 3.0 or later, which means that https://github.com/edemaine/meteor-file-collection doesn't support it, as it uses driver version 2.1.21 - https://github.com/edemaine/meteor-file-collection/blob/master/package.js#L18

I tried using the URI without `+srv` i.e., specifying the replicaset directly, but then I came across a strange TLS error that shouldn't happen:

> 2020-06-17T21:25:48.430854+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:313
2020-06-17T21:25:48.430856+00:00 app[web.1]: throw(ex);
2020-06-17T21:25:48.430857+00:00 app[web.1]: ^
2020-06-17T21:25:48.434161+00:00 app[web.1]: Error [ERR_TLS_CERT_ALTNAME_INVALID] [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: abc.xyz.gcp.mongodb.net. is not in the cert's altnames: DNS:*.gcp.mongodb.net, DNS:gcp.mongodb.net
2020-06-17T21:25:48.434162+00:00 app[web.1]: at Object.checkServerIdentity (tls.js:288:12)
2020-06-17T21:25:48.434162+00:00 app[web.1]: at TLSSocket.onConnectSecure (_tls_wrap.js:1483:27)
2020-06-17T21:25:48.434163+00:00 app[web.1]: at TLSSocket.emit (events.js:311:20)
2020-06-17T21:25:48.434163+00:00 app[web.1]: at TLSSocket.EventEmitter.emit (domain.js:482:12)
2020-06-17T21:25:48.434163+00:00 app[web.1]: at TLSSocket._finishInit (_tls_wrap.js:916:8)
2020-06-17T21:25:48.434164+00:00 app[web.1]: at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12) {
2020-06-17T21:25:48.434164+00:00 app[web.1]: name: 'MongoError',
2020-06-17T21:25:48.434167+00:00 app[web.1]: message: "Hostname/IP does not match certificate's altnames: Host: abc.xyz.gcp.mongodb.net. is not in the cert's altnames: DNS:*.gcp.mongodb.net, DNS:gcp.mongodb.net"
2020-06-17T21:25:48.434167+00:00 app[web.1]: }
2020-06-17T21:25:48.501741+00:00 heroku[web.1]: Process exited with status 1

I checked the SAN's manually via `openssl` command and the altnames are definitely there, but the driver somehow shows different altnames. I think this could be another bug with the older driver version used in file-collection, but I don't have proof to confirm that yet...

A potential fix could be to update the driver version of the meteor file collection. I could try updating it for my own situation by forking it and make it work like that perhaps, in order to avoid potentially breaking anything for other users.

Cheers!

**Comment by edemaine** [comment]
Ah, I see -- that makes sense. Thanks for explaining! I'll try updating `edemaine:file-collection` to see whether it breaks anything for me; if not, I can publish that change and it will hopefully help your situation.

**Comment by jammm** [comment]
Thank you ! Yes it would be interesting to see if it breaks anything. FWIW, I could always move away from MongoDB atlas and use some other service with older MongoDB versions as my original intention was to try this out with my labmates. So even if this doesn't work, it doesn't matter for me. At the very least, this issue can help others who might have a similar issue in the future.

**Comment by edemaine** [comment]
FYI, I gave a try at this, and it's not as easy as I'd hoped, but still probably possible. The changes to the MongoDB Driver API impact a bunch of `file-collection`; at least, it breaks some of its built-in tests. I did get it working enough for Coauthor file uploads/downloads to seem to work, but with lots of warnings about use of outdated driver method names which should ideally be corrected. So this will probably be a while before it's ready for primetime.

On the other hand, if it's helpful to you, you can try the rough draft I have now. Here's how:

* `cd` to `coauthor` directory
* `mkdir packages`
* `cd packages`
* `git clone -b mongo-driver-3 https://github.com/edemaine/meteor-file-collection.git`

If you try it, let me know how it goes!

**Comment by jammm** [comment]
It works! Thank you so much for the quick response. I really appreciate it ^_^

I'll post here again if I face any breaking issues. If not, I'll close this issue soon.

Cheers,
jam

**Comment by jammm** [comment]
Okay, I created a group and created a new post, but the text editor seems to be stuck in "loading..." 
![image](https://user-images.githubusercontent.com/2500920/85118844-d3004600-b25b-11ea-9103-7d41a6690d6a.png)
****

**Comment by jammm** [comment]
AH! I think I found the issue. 
```
Access to XMLHttpRequest at 'https://abc.herokuapp.com/channel/test?a=azzz&VER=8&MODE=init&zx=zzzzz&t=1' from origin 'https://xyz.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

This is something I probably have to fix on my side via heroku. I'll post here if this fixed the above issue.

**Comment by jammm** [comment]
It's fixed! Just had to fix ROOT_URL.

Thanks a lot for the support :)

I'll post here if I encounter any further issues.

**Comment by edemaine** [comment]
FYI, I recently rewrote [file-collection](https://github.com/edemaine/meteor-file-collection) to use the latest MongoDB interface, so you should no longer need this workaround if you upgrade to the latest version of Coauthor.
