### ISSUE TITLE
mup deploy failing after update

### ISSUE THREAD

**Issue by lvanbever** [edemaine/coauthor#492]
Hi Erik,

`mup deploy` fails with this error message following an update to the latest commit. I'm guessing I forgot to do something obvious? Could it be due to the meteor upgrade?

```
Building App Bundle Locally
/local/home/vlaurent/.meteor/packages/meteor-tool/.1.11.1.qfeawx.9tywm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received null
    at validateString (internal/validators.js:120:11)
    at Object.relative (path.js:1054:5)
    at Object.wrapper [as pathRelative] (/local/home/vlaurent/.meteor/packages/meteor-tool/.1.11.1.qfeawx.9tywm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/static-assets/server/tools/static-assets/server/mini-files.ts:107:14)
    at isWithinProdPackage (/tools/isobuild/bundler.js:467:27)
    at isWithinProdPackage (/tools/isobuild/bundler.js:494:18)
    at /tools/isobuild/builder.js:724:15
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at /tools/isobuild/builder.js:734:11
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at Builder._copyDirectory (/tools/isobuild/builder.js:788:5)
    at Builder.copyNodeModulesDirectory (/tools/isobuild/builder.js:550:17)
    at /tools/isobuild/bundler.js:2482:17
    at Function._.each._.forEach (/local/home/vlaurent/.meteor/packages/meteor-tool/.1.11.1.qfeawx.9tywm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at JsImage.write (/tools/isobuild/bundler.js:2439:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2694:13)
    at /tools/isobuild/bundler.js:2861:30
    at /tools/isobuild/bundler.js:3000:11
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:2995:26
    at /tools/isobuild/bundler.js:3355:22
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3169:31)
    at /tools/isobuild/bundler.js:3113:32
    at Slot.withValue (/local/home/vlaurent/.meteor/packages/meteor-tool/.1.11.1.qfeawx.9tywm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at Object.withCache (/local/home/vlaurent/.meteor/packages/meteor-tool/.1.11.1.qfeawx.9tywm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1659:39)
    at Object.bundle (/tools/isobuild/bundler.js:3113:16)
    at buildCommand (/tools/cli/commands.js:1087:30)
    at /tools/cli/commands.js:950:25
    at Function.run (/local/home/vlaurent/.meteor/packages/meteor-tool/.1.11.1.qfeawx.9tywm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at /tools/cli/commands.js:948:18
    at /local/home/vlaurent/.meteor/packages/meteor-tool/.1.11.1.qfeawx.9tywm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/local/home/vlaurent/.meteor/packages/meteor-tool/.1.11.1.qfeawx.9tywm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at /tools/cli/main.js:1529:7 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by lvanbever** [comment]
I found a way so closing the issue. For those of you who may experience this problem in the future: cleaning my `node_modules` folder followed by a `mup setup`, `mup deploy` did the trick!

**Comment by edemaine** [comment]
Odd. Not sure what caused that error, but glad you got it working!
