### ISSUE TITLE
Unable to run meteor

### ISSUE THREAD

**Issue by mynameismon** [edemaine/coauthor#589]
## What's wrong?
On running the steps reffered to in the [installation guide](https://github.com/edemaine/coauthor/blob/main/INSTALL.md), and starting the app by running ``meteor``, I am greeted with a massive wall of text

## How to Reproduce
1. Clone the repository into a fresh VM
2. Run ``meteor npm install``
3. Run ``meteor``

## Logs:
```log
[[[[[ ~\D\coauthor\coauthor ]]]]]

=> Started proxy.
=> Meteor 2.5 is available. Update this project with 'meteor update'.
=> Errors prevented startup:

   While processing files with coagmano:stylus (for target web.browser):
   fs.js:462:3: ENOENT: no such file or directory, open
   '/Users/Monish/AppData/Local/.meteor/packages/coagmano_stylus/1.1.0/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/nib/lib/nib/flex.styl'
   at Object.openSync (fs.js:462:3)
   at Object.readFileSync (fs.js:364:35)
   at readFile (packages/compileStylusBatch/plugin/compile-stylus.js:169:36)
   at Array.map (<anonymous>)
   at processSourcemap (packages/compileStylusBatch/plugin/compile-stylus.js:189:52)
   at StylusCompiler.compileOneFile (packages/compileStylusBatch/plugin/compile-stylus.js:311:23)
   at getResult (packages/caching-compiler/multi-file-caching-compiler.js:113:32)
   at packages/compileStylusBatch/plugin/compile-stylus.js:61:30
   at
   C:\Users\Monish\AppData\Local\.meteor\packages\mquandalle_jade\0.4.9\plugin.compileJadeBatch.os\npm\node_modules\meteor\promise\promise\node_modules\meteor-promise\fiber_pool.js:33:40


   While processing files with coagmano:stylus (for target web.browser.legacy):
   fs.js:462:3: ENOENT: no such file or directory, open
   '/Users/Monish/AppData/Local/.meteor/packages/coagmano_stylus/1.1.0/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/nib/lib/nib/flex.styl'
   at Object.openSync (fs.js:462:3)
   at Object.readFileSync (fs.js:364:35)
   at readFile (packages/compileStylusBatch/plugin/compile-stylus.js:169:36)
   at Array.map (<anonymous>)
   at processSourcemap (packages/compileStylusBatch/plugin/compile-stylus.js:189:52)
   at StylusCompiler.compileOneFile (packages/compileStylusBatch/plugin/compile-stylus.js:311:23)
   at getResult (packages/caching-compiler/multi-file-caching-compiler.js:113:32)
   at packages/compileStylusBatch/plugin/compile-stylus.js:61:30
   at
   C:\Users\Monish\AppData\Local\.meteor\packages\mquandalle_jade\0.4.9\plugin.compileJadeBatch.os\npm\node_modules\meteor\promise\promise\node_modules\meteor-promise\fiber_pool.js:33:40


   While processing files with coagmano:stylus (for target web.cordova):
   fs.js:462:3: ENOENT: no such file or directory, open
   '/Users/Monish/AppData/Local/.meteor/packages/coagmano_stylus/1.1.0/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/nib/lib/nib/flex.styl'
   at Object.openSync (fs.js:462:3)
   at Object.readFileSync (fs.js:364:35)
   at readFile (packages/compileStylusBatch/plugin/compile-stylus.js:169:36)
   at Array.map (<anonymous>)
   at processSourcemap (packages/compileStylusBatch/plugin/compile-stylus.js:189:52)
   at StylusCompiler.compileOneFile (packages/compileStylusBatch/plugin/compile-stylus.js:311:23)
   at getResult (packages/caching-compiler/multi-file-caching-compiler.js:113:32)
   at packages/compileStylusBatch/plugin/compile-stylus.js:61:30
   at
   C:\Users\Monish\AppData\Local\.meteor\packages\mquandalle_jade\0.4.9\plugin.compileJadeBatch.os\npm\node_modules\meteor\promise\promise\node_modules\meteor-promise\fiber_pool.js:33:40
```

## Context
 - Device/OS: Windows (x64)
 - Coauthor server: meteor

**Comment by edemaine** [comment]
This looks like a transient network error. You should probably try deleting the Meteor package cache and running Meteor again. I doubt it's a Coauthor issue.

**Comment by mynameismon** [comment]
Well, I tried that, and it doesn't fix it. It does seem like a meteor issue, though.

**Comment by edemaine** [comment]
For what it's worth, the file `AppData/Local/.meteor/packages/coagmano_stylus/1.1.0/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/nib/lib/nib/flex.styl` (the one in your error message) exists for me. Does it exist for you?

**Comment by mynameismon** [comment]
That's the first thing I had checked too, and yes, it was there then.

**Comment by edemaine** [comment]
Are you saying it's working now? If so, yay!

**Comment by mynameismon** [comment]
I really wish!
Nope, I have the file, but the error still shows up after checking in the latest commit.

**Comment by edemaine** [comment]
Weird. I looked at the diff since version `before-react`, and the `coagmano:stylus` package was added since.  So perhaps that's the problem somehow.  You might try:

* Updating the `coagmano:stylus` dependency to `@2.0.0` (in `.meteor/packages`). This version is very slow in my experience, but it's the latest, so maybe it works?
* Opening an issue at https://github.com/Meteor-Community-Packages/meteor-stylus/issues

I'm still unable to reproduce the issue. I just tried upgrading my Meteor CLI (but not the Meteor version of Coauthor &mdash; that seems to require more work) and I can still run `meteor` fine.  I haven't tried `npm install meteor` from a clean machine though; I'm still using the Chocolately based install (so you could try that too).
